import {useEffect,useState} from 'react';import {Save,Upload,Store} from 'lucide-react';import {shopAPI} from '../../services/api';
export default function ShopSettings(){const [form,setForm]=useState({shopName:'Mobile Shop',phone:'',email:'',address:'',currency:'Rs',logo:''});const [saved,setSaved]=useState(false);
useEffect(()=>{shopAPI.get().then(r=>setForm(r.data.data))},[]);
const change=e=>setForm({...form,[e.target.name]:e.target.value});
const logo=e=>{const f=e.target.files?.[0];if(!f)return;const rd=new FileReader();rd.onload=()=>setForm(x=>({...x,logo:rd.result}));rd.readAsDataURL(f)};
const submit=async e=>{e.preventDefault();await shopAPI.save(form);setSaved(true);setTimeout(()=>setSaved(false),1800)};
return <div className="max-w-4xl mx-auto"><div className="mb-6"><h2 className="text-2xl font-extrabold text-slate-900">Shop Profile</h2><p className="text-slate-500">Save once — these details stay permanent and will be used on invoices.</p></div><form onSubmit={submit} className="card"><div className="card-body p-6 md:p-8">
<div className="flex flex-col md:flex-row gap-7 mb-8"><div className="w-32 h-32 rounded-3xl border border-blue-100 bg-blue-50 flex items-center justify-center overflow-hidden shadow-inner">{form.logo?<img src={form.logo} className="w-full h-full object-contain"/>:<Store className="w-12 h-12 text-blue-500"/>}</div><div><h3 className="font-bold text-lg">Shop Logo / DP</h3><p className="text-sm text-slate-500 mb-3">This logo will also appear on PDF invoices.</p><label className="btn btn-secondary inline-flex items-center gap-2 cursor-pointer"><Upload className="w-4 h-4"/>Upload Logo<input type="file" accept="image/*" className="hidden" onChange={logo}/></label></div></div>
<div className="grid md:grid-cols-2 gap-5">{[['shopName','Shop / App Name'],['phone','Phone / WhatsApp'],['email','Email'],['address','Address']].map(([n,l])=><label key={n} className="text-sm font-semibold text-slate-700">{l}<input name={n} value={form[n]||''} onChange={change} className="input mt-1.5"/></label>)}<label className="text-sm font-semibold text-slate-700">Default Currency<input value="Rs" disabled className="input mt-1.5 bg-slate-50"/></label></div>
<div className="mt-7 flex items-center gap-3"><button className="btn btn-primary flex items-center gap-2"><Save className="w-4 h-4"/>Save Permanently</button>{saved&&<span className="text-emerald-600 font-semibold">Saved ✓</span>}</div></div></form></div>}